racket 01-line.rkt
racket 02-rectangle.rkt
racket 03-basic-styles.rkt
racket 04-no-smoothing.rkt
racket 05-smoothed.rkt
racket 06-aligned.rkt
racket 07-smoothed-horlines.rkt
racket 08-aligned-horlines.rkt
racket 09-pen-styles.rkt
racket 10-pen-cap.rkt
racket 11-brushes.rkt
racket 12-gradient.rkt
racket 13-paths.rkt
racket 14-racket-logo.rkt
racket 15-racket-logo.rkt
racket 16-spline.rkt
racket 17-alpha.rkt
racket 18-text.rkt
racket 19-turtles.rkt
racket 20-turtles-repeat.rkt
racket 21-turtles-move-offset.rkt
racket 22-turtles-nested-repeats.rkt
racket 23-turtles-no-split.rkt
racket 24-turtles-split.rkt
racket 25-radial-turtles.rkt
