(define (compute-pi n)
  (let ((pi 4.0))
    (let loop ((i 3))
      (set! pi (* pi (/ (- i 1) i) (/ (+ i 1) i)))
      (if (<= i (+ n 2)) (loop (+ i 2))))
    pi))
 
(let loop ((n 1))
  (display n)
  (display " ")
  (display (compute-pi n))
  (newline)
  (if (<= n 10000000)
      (loop (* n 2))))
