(defun C:obdelnik()
  (setq bod1 (getpoint "\nZadej počáteční bod obdélníka: ") )
  (setq bod3 (getpoint "\nZadej protilehlý bod obdélníka: ") )
  (setq bod2 (list (car bod3) (cadr bod1) ) )
  (setq bod4 (list (car bod1) (cadr bod3) ) )
  (command "PLINE" bod1 bod2 bod3 bod4 "CLOSE"))
