guile closure_1.scm > closure_1.out
guile closure_2.scm > closure_2.out
guile closure_3.scm > closure_3.out
guile closure_4.scm > closure_4.out
guile cons.scm > cons.out
guile dot_pairs.scm > dot_pairs.out
guile factorial_1.scm > factorial_1.out
guile factorial_2.scm > factorial_2.out
guile factorial_3.scm > factorial_3.out
guile functions.scm > functions.out
guile lexical_scope_1.scm > lexical_scope_1.out
guile lexical_scope_2.scm > lexical_scope_2.out
guile lexical_scope_3.scm > lexical_scope_3.out
guile lexical_scope_4.scm > lexical_scope_4.out
guile lists.scm > lists.out
